image: marcoturi/ionic:latest

stages:
  - build
  - test
  - deploy

before_script:
  - yarn config set cache-folder .yarn
  - yarn

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/
    - .yarn

build_web:
  stage: build
  script:
    - npm run build
test:
  stage: test
  script:
    - echo "Do Nothing"

build_ios:
  stage: deploy
  only:
    - web
    - pipelines
  script:
    - ./sh/ionic-login.sh
    - ls
    - npm run ios:release:ci
    - ./sh/ionic-package-ios.sh

build_android:
  stage: deploy
  only:
    - web
    - pipelines
  script:
    - ls
    - ionic cordova platform rm android
    - ionic cordova platform add android
    - npm run android:release
    - ls ./platforms/android/build/outputs/apk/android*.apk
  artifacts:
    paths:
      - platforms/android/build/outputs/apk/
