image: lkdevelopment/ionic-docker:latest

stages:
  - build
  - deploy

before_script:
  - apt-get update >/dev/null
  - apt-get install -y locales >/dev/null
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8
  - yarn config set cache-folder .yarn
  - yarn

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/
    - .yarn

build_web:
  stage: build
  script:
    - npm run build

build_ios:
  stage: deploy
  script:
    - npm run ios:release:ci
    - ./sh/ionic-package-ios.sh

build_android:
  stage: deploy
  script:
    - ls
    - ionic cordova platform rm android
    - ionic cordova platform add android
    - npm run android:release
    - ls ./platforms/android/build/outputs/apk/android*.apk
  artifacts:
    paths:
      - platforms/android/build/outputs/apk/
